name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yaml"
      - "Makefile"
      - "Dockerfile"
      - ".dockerignore"
      - "action.yml"
      - "entrypoint.sh"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yaml"
      - "Makefile"
      - "Dockerfile"
      - ".dockerignore"
      - "action.yml"
      - "entrypoint.sh"
  workflow_dispatch:
    inputs:
      semver_type:
        description: "Semver type"
        required: true
        type: "choice"
        options:
          - "patch"
          - "minor"
          - "major"
        default: "patch"

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0
        with:
          fetch-depth: 0

      - uses: ./
        id: envs

      - run: make build
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ steps.envs.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_CACHE_URL: ${{ steps.envs.outputs.ACTIONS_CACHE_URL }}

      - run: make login
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make push
        if: github.event_name != 'pull_request'

      - uses: peaceiris/workflows/setup-git@v0.18.1

      - run: make release
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMVER_TYPE: ${{ github.event.inputs.semver_type }}
